repos:
  - repo: local
    hooks:
    - id: lint
      name: lint
      entry: task lint
      language: system
      types: [python]
      pass_filenames: false
      exclude: "src/\\*test\\*.py"
    - id: format
      name: format
      entry: task format
      language: system
      types: [python]
      pass_filenames: false
      exclude: "src/\\*test\\*.py"

