# cspell: disable
version: "3"

tasks:
  default:
    - task: fix
    - task: format

  lint:
    cmds:
      - ruff check --respect-gitignore src
      - pyright src

  format:
    cmd: ruff format --respect-gitignore src

  fix:
    cmd: ruff check --respect-gitignore --fix src

  dev-install:
    cmds:
      - pip install --upgrade uv
      - uv pip install --upgrade ruff pyright pre-commit

  setup-venv:
    cmds:
      - python3 -m venv .venv
      - source .venv/bin/activate

  dev-setup:
    deps:
      - task: setup-venv
      - task: dev-install
      - task: create-config
    cmds:
      - pre-commit install

  clean:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - rm -rf site release_body.md .*_cache *.log

  release:
    deps:
      - task: dev-setup
    cmd: python3 tools/release.py
